export const workExperienceData = [
  {
    position: "Senior Software Engineer",
    company: "Tech Innovations Inc.",
    fromYear: "June 2018",
    toYear: "Present",
    location: "San Francisco, CA",
    tasks: [
      "Lead a team of developers in building and maintaining scalable web applications.",
      "Collaborate with cross-functional teams to define software requirements and specifications.",
      "Implement new features and enhancements using react and Node.js.",
      "Conduct code reviews and mentor junior team members.",
      "Optimize application performance and troubleshoot issues.",
      "Integrate third-party APIs to enhance functionality.",
    ],
    technologies: ["angular", "javascript", "typescript", "css", "mongodb"],
  },
  {
    position: "Product Manager",
    fromYear: "January 2016",
    toYear: "March 2018",
    company: "InnovateTech Solutions",
    location: "New York, NY",
    tasks: [
      "Define product vision, strategy, and roadmaps.",
      "Gather and prioritize product requirements from stakeholders and customers.",
      "Work closely with design and development teams to ensure successful product delivery.",
      "Analyze market trends and competition to identify new opportunities.",
      "Conduct user interviews and surveys to gather feedback.",
      "Coordinate product launches and marketing efforts.",
    ],
    technologies: ["react", "javascript", "html", "css", "mongodb"],
  },
  {
    position: "UX/UI Designer",
    fromYear: "September 2014",
    toYear: "December 2015",
    company: "Creative Design Studio",
    location: "Los Angeles, CA",
    tasks: [
      "Design and prototype user interfaces for web and mobile applications.",
      "Conduct usability testing and gather user feedback for iterative design improvements.",
      "Collaborate with developers to implement responsive and user-friendly designs.",
      "Create design assets, including wireframes, mockups, and style guides.",
      "Stay up-to-date with design trends and tools.",
    ],
    technologies: ["react", "javascript", "html", "css", "mongodb"],
  },
  {
    position: "Software Engineer Intern",
    fromYear: "May 2013",
    toYear: "August 2013",
    company: "TechStart Innovations",
    location: "San Francisco, CA",
    tasks: [
      "Assisted in the development of new features for a cloud-based analytics platform.",
      "Collaborated with senior engineers to troubleshoot and debug issues.",
      "Participated in code reviews and learned best practices in software development.",
      "Gained hands-on experience with technologies such as Java and Spring Framework.",
    ],
    technologies: ["react", "javascript", "html", "css", "mongodb"],
  },
]
