const avatarData = [
    {
        firstName: 'Ann',
        lastName: 'Lewis',
        email: 'bdoyle@smith.com',
        number: '(916)799-5297x873',
        isPaid: 'False',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdnBt',
        secretCode: 'UUu###',
        age: '41',
        address: '55073 Nathan Summit\nTuckerbury, SC 52591',
        imageUrl: 'https://www.lorempixel.com/712/606',
        gender: 'non-binary',
        teamId: 't1',
    },
    {
        firstName: 'Derek',
        lastName: 'Carpenter',
        email: 'smason@hotmail.com',
        number: '2572741641',
        isPaid: 'True',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdbxd',
        secretCode: 'Ssm###',
        age: '52',
        address: '946 Tucker Hill Apt. 108\nLake Lisaside, OK 10945',
        imageUrl: 'https://placeimg.com/324/630/any',
        gender: 'non-binary',
        teamId: 't2',
    },
    {
        firstName: 'Jon',
        lastName: 'Collier',
        email: 'miguel49@cummings-gregory.com',
        number: '705-448-8855x81308',
        isPaid: 'False',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdLss',
        secretCode: 'QZP###',
        age: '78',
        address: '19727 Destiny Crossing Apt. 665\nLake Carolhaven, WV 71905',
        imageUrl: 'https://www.lorempixel.com/790/717',
        gender: 'male',
        teamId: 't1',
    },
    {
        firstName: 'James',
        lastName: 'Webb',
        email: 'khunter@gmail.com',
        number: '686-226-8650',
        isPaid: 'True',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdNte',
        secretCode: 'eZn###',
        age: '67',
        address: '559 Lisa Street Apt. 977\nNew Melissa, ID 53832',
        imageUrl: 'https://placekitten.com/46/945',
        gender: 'non-binary',
        teamId: 't3',
    },
    {
        firstName: 'David',
        lastName: 'Fleming',
        email: 'jacksongene@cain-ross.com',
        number: '(014)100-7900x903',
        isPaid: 'False',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdYBf',
        secretCode: 'IBB###',
        age: '48',
        address: '9658 Nguyen Heights Suite 082\nCoxborough, WA 83300',
        imageUrl: 'https://dummyimage.com/102x873',
        gender: 'male',
        teamId: 't4',
    },
    {
        firstName: 'Anthony',
        lastName: 'Lucas',
        email: 'fnelson@yahoo.com',
        number: '0088604695',
        isPaid: 'True',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdyJV',
        secretCode: 'xCh###',
        age: '35',
        address: '04064 Laura Parks\nCurtisview, UT 63280',
        imageUrl: 'https://placekitten.com/136/196',
        gender: 'non-binary',
        teamId: 't4',
    },
    {
        firstName: 'Brian',
        lastName: 'Butler',
        email: 'yerickson@martinez.biz',
        number: '(161)928-4579',
        isPaid: 'True',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdLEZ',
        secretCode: 'zlQ###',
        age: '33',
        address: '91258 Amy Oval\nNew Susan, VT 62380',
        imageUrl: 'https://www.lorempixel.com/395/840',
        gender: 'male',
        teamId: 't4',
    }, {
        firstName: 'Heather',
        lastName: 'Solis',
        email: 'jesusmorse@hotmail.com',
        number: '(715)860-9168x38009',
        isPaid: 'True',
        sessionId: 'sessionIdNqcuiM',
        linkId: 'linkIdKZk',
        secretCode: 'urF###',
        age: '52',
        address: '64167 Simpson Drive Apt. 187\nBenjaminport, HI 02543',
        imageUrl: 'https://dummyimage.com/555x874',
        gender: 'non-binary',
        teamId: 't2',
    }
]


const sessionData = [
    {
        sessionId: 'sessionIdNqcuiM',
        sessionName: 'Bridgetown',
        time: '8pm',
        maxNumberOfPlayers: 80,
        maxNumberOfPlayerPerTeam: 8,
        teams: [{
            teamId: 't1',
            teamName: 'Green Team',
            teamColor: 'green'
        },
        {
            teamId: 't2',
            teamName: 'Red Team',
            teamColor: 'red'
        },
        {
            teamId: 't3',
            teamName: 'Blue Team',
            teamColor: 'blue'
        },
        {
            teamId: 't4',
            teamName: 'White Team',
            teamColor: 'white'
        },
        ],
        sessionPrice: '350php',
        avatarjoined: [{
            firstName: 'Ann',
            lastName: 'Lewis',
            email: 'bdoyle@smith.com',
            number: '(916)799-5297x873',
            isPaid: 'False',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdnBt',
            secretCode: 'UUu###',
            age: '41',
            address: '55073 Nathan Summit\nTuckerbury, SC 52591',
            imageUrl: 'https://www.lorempixel.com/712/606',
            gender: 'non-binary',
            teamId: 't1',
        },
        {
            firstName: 'Derek',
            lastName: 'Carpenter',
            email: 'smason@hotmail.com',
            number: '2572741641',
            isPaid: 'True',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdbxd',
            secretCode: 'Ssm###',
            age: '52',
            address: '946 Tucker Hill Apt. 108\nLake Lisaside, OK 10945',
            imageUrl: 'https://placeimg.com/324/630/any',
            gender: 'non-binary',
            teamId: 't2',
        },
        {
            firstName: 'Jon',
            lastName: 'Collier',
            email: 'miguel49@cummings-gregory.com',
            number: '705-448-8855x81308',
            isPaid: 'False',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdLss',
            secretCode: 'QZP###',
            age: '78',
            address: '19727 Destiny Crossing Apt. 665\nLake Carolhaven, WV 71905',
            imageUrl: 'https://www.lorempixel.com/790/717',
            gender: 'male',
            teamId: 't1',
        },
        {
            firstName: 'James',
            lastName: 'Webb',
            email: 'khunter@gmail.com',
            number: '686-226-8650',
            isPaid: 'True',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdNte',
            secretCode: 'eZn###',
            age: '67',
            address: '559 Lisa Street Apt. 977\nNew Melissa, ID 53832',
            imageUrl: 'https://placekitten.com/46/945',
            gender: 'non-binary',
            teamId: 't3',
        },
        {
            firstName: 'David',
            lastName: 'Fleming',
            email: 'jacksongene@cain-ross.com',
            number: '(014)100-7900x903',
            isPaid: 'False',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdYBf',
            secretCode: 'IBB###',
            age: '48',
            address: '9658 Nguyen Heights Suite 082\nCoxborough, WA 83300',
            imageUrl: 'https://dummyimage.com/102x873',
            gender: 'male',
            teamId: 't4',
        },
        {
            firstName: 'Anthony',
            lastName: 'Lucas',
            email: 'fnelson@yahoo.com',
            number: '0088604695',
            isPaid: 'True',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdyJV',
            secretCode: 'xCh###',
            age: '35',
            address: '04064 Laura Parks\nCurtisview, UT 63280',
            imageUrl: 'https://placekitten.com/136/196',
            gender: 'non-binary',
            teamId: 't4',
        },
        {
            firstName: 'Brian',
            lastName: 'Butler',
            email: 'yerickson@martinez.biz',
            number: '(161)928-4579',
            isPaid: 'True',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdLEZ',
            secretCode: 'zlQ###',
            age: '33',
            address: '91258 Amy Oval\nNew Susan, VT 62380',
            imageUrl: 'https://www.lorempixel.com/395/840',
            gender: 'male',
            teamId: 't4',
        }, {
            firstName: 'Heather',
            lastName: 'Solis',
            email: 'jesusmorse@hotmail.com',
            number: '(715)860-9168x38009',
            isPaid: 'True',
            sessionId: 'sessionIdNqcuiM',
            linkId: 'linkIdKZk',
            secretCode: 'urF###',
            age: '52',
            address: '64167 Simpson Drive Apt. 187\nBenjaminport, HI 02543',
            imageUrl: 'https://dummyimage.com/555x874',
            gender: 'non-binary',
            teamId: 't2',
        }],
        founderId:
    }
]