export const positionTitles = [
  "All",
  "Full Stack Developer",
  "Backend Developer",
  "Frontend Developer",
  "UI/UX Designer",
  "Video Editor",
  "Virtual Assistant",
  "Shopify Developer",
  "Wordpress Developer",
  "Human Resource",
  "Project Manager",
  "Social Media Manager",
  "Fb Ads Specialist",
  "Research Auditor",
]

export const interns = [
  {
    id: 1,
    name: "John Smith",
    position: "Full Stack Developer",
    imageUrl: "/projectsCompletedAssets/image1.png",
    backgroundColor: "bg-darkBlueBgColor",
  },
  {
    id: 2,
    name: "Alice Johnson",
    position: "Frontend Developer",
    imageUrl: "/projectsCompletedAssets/image2.png",
    backgroundColor: "bg-redBgColor",
  },
  {
    id: 3,
    name: "Eva Davis",
    position: "UI/UX Designer",
    imageUrl: "/projectsCompletedAssets/image3.png",
    backgroundColor: "bg-violetBgColor",
  },
  {
    id: 4,
    name: "Bob Williams",
    position: "Frontend Developer",
    imageUrl: "/projectsCompletedAssets/image4.png",
    backgroundColor: "bg-greenBgColor",
  },
  {
    id: 5,
    name: "Chris Turner",
    position: "Full Stack Developer",
    imageUrl: "/projectsCompletedAssets/image5.png",
    backgroundColor: "bg-darkBlueBgColor",
  },
  {
    id: 6,
    name: "Sophie Wilson",
    position: "Backend Developer",
    imageUrl: "/projectsCompletedAssets/image3.png",
    backgroundColor: "bg-redBgColor",
  },
  {
    id: 7,
    name: "Daniel Brown",
    position: "Virtual Assistant",
    imageUrl: "/projectsCompletedAssets/image1.png",
    backgroundColor: "bg-violetBgColor",
  },
  {
    id: 8,
    name: "Emma White",
    position: "Frontend Developer",
    imageUrl: "/projectsCompletedAssets/image5.png",
    backgroundColor: "bg-greenBgColor",
  },
  {
    id: 9,
    name: "Alex Turner",
    position: "Full Stack Developer",
    imageUrl: "/projectsCompletedAssets/image4.png",
    backgroundColor: "bg-darkBlueBgColor",
  },
  {
    id: 10,
    name: "Grace Taylor",
    position: "Frontend Developer",
    imageUrl: "/projectsCompletedAssets/image2.png",
    backgroundColor: "bg-redBgColor",
  },
]
